# Generated by Django 4.0.2 on 2022-02-23 12:32

from django.db import migrations, models
import functools
import random
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=uuid.UUID('e7596f2c-63cd-451a-93a0-37e6cb006fed'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.IntegerField(default=functools.partial(random.Random.randint, *(1000, 10000), **{})),
        ),
    ]
