# Generated by Django 4.0.2 on 2022-02-23 12:35

from django.db import migrations, models
import functools
import random
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.UUIDField(default=uuid.UUID('ff9f7e93-4a78-4416-aa3f-a5df77cc101e'), unique=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.IntegerField(default=functools.partial(random.Random.randint, *(1000, 10000), **{})),
        ),
    ]
