# Generated by Django 4.0.2 on 2022-02-23 12:41

from django.db import migrations, models
import functools
import random
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=uuid.UUID('91abfbf9-6820-4f1b-aa93-48dc0f1768b9'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.IntegerField(default=functools.partial(random.Random.randint, *(1000, 10000), **{})),
        ),
    ]
