# Generated by Django 4.0.2 on 2022-02-23 19:14

from django.db import migrations, models
import functools
import random


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_username_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.IntegerField(default=functools.partial(random.Random.randint, *(1000, 10000), **{})),
        ),
    ]
