# Generated by Django 4.0.2 on 2022-03-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='otptoken',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='otptoken',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='otptoken',
            name='check_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
