# Generated by Django 4.0.2 on 2022-03-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_otptoken_attempts_remove_otptoken_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='call_phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
