# Generated by Django 4.0.2 on 2022-03-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user_username',
        ),
    ]
